_id: cnnpyxypoanjonon
name: Training Kit, Bird
type: loot
img: systems/pf1/icons/items/inventory/dice.jpg
system:
  description:
    value: >-
      <p><b>Price</b> 17 gp; <b>Weight</b> 8 lbs.</p>

      <p>This kit includes a falconry gauntlet, Tiny cage, training whip, and 2
      days' worth of bird feed.</p>
  weight:
    value: 8
  price: 17
  equipped: false
  subType: gear
  source:
    id: PZO9410
_key: '!items!cnnpyxypoanjonon'

