_id: uwwpglorqzzefcom
_key: '!items!uwwpglorqzzefcom'
img: systems/pf1/icons/items/inventory/dice.jpg
name: Training Kit, Beast
system:
  description:
    value: >-
      <p><b>Price</b> 15 gp; <b>Weight</b> 26 lbs.</p>

      <p>This kit includes a dandy brush, training harness, training whip, whet
      bone, and 2 days' worth of carnivore feed. The weight of this kit can be
      reduced by 10 pounds by forgoing the carnivore feed.</p>
  equipped: false
  price: 15
  source:
    id: PZO9410
  subType: gear
  weight:
    value: 26
type: loot

