export const DefaultData_Materials = [
  {
    id: "mt-steel",
    name: "Steel",
    img: "icons/commodities/metal/ingot-plain-steel.webp",
    hardness: 10,
    hpPer: 30,
    bypassesDR: [],
  },
  {
    id: "mt-coldiron",
    name: "Cold Iron",
    img: "icons/commodities/metal/ingot-worn-steel.webp",
    hardness: 10,
    hpPer: 30,
    bypassesDR: ["dr-coldiron"],
  },
  {
    id: "mt-alchsilver",
    name: "Alchemical Silver",
    img: "icons/commodities/metal/ingot-engraved-silver.webp",
    hardness: 8,
    hpPer: 10,
    bypassesDR: ["dr-silver"],
  },
  {
    id: "mt-mithral",
    name: "Mithral",
    img: "icons/commodities/metal/ingot-stamped-silver.webp",
    hardness: 15,
    hpPer: 30,
    bypassesDR: ["dr-silver"],
  },
  {
    id: "mt-adamantine",
    name: "Adamantine",
    img: "icons/commodities/metal/ingot-stamped-purple.webp",
    hardness: 20,
    hpPer: 40,
    bypassesDR: ["dr-adamantine"],
  },
  {
    id: "mt-glass",
    name: "Glass",
    img: "icons/tools/laboratory/alembic-glass-ball-blue.webp",
    hardness: 1,
    hpPer: 1,
    bypassesDR: [],
  },
  {
    id: "mt-paper",
    name: "Paper",
    img: "icons/sundries/documents/paper-plain-white.webp",
    hardness: 0,
    hpPer: 2,
    bypassesDR: [],
  },
  {
    id: "mt-cloth",
    name: "Cloth",
    img: "icons/commodities/cloth/cloth-bolt-yellow.webp",
    hardness: 0,
    hpPer: 2,
    bypassesDR: [],
  },
  {
    id: "mt-ice",
    name: "Ice",
    img: "icons/magic/water/barrier-ice-crystal-wall-faceted.webp",
    hardness: 0,
    hpPer: 3,
    bypassesDR: [],
  },
  {
    id: "mt-leather",
    name: "Leather",
    img: "icons/commodities/leather/leather-bolt-tan.webp",
    hardness: 2,
    hpPer: 5,
    bypassesDR: [],
  },
  {
    id: "mt-wood",
    name: "Wood",
    img: "icons/commodities/wood/lumber-stack.webp",
    hardness: 5,
    hpPer: 10,
    bypassesDR: [],
  },
  {
    id: "mt-stone",
    name: "Stone",
    img: "icons/commodities/stone/ore-chunk-grey.webp",
    hardness: 8,
    hpPer: 15,
    bypassesDR: [],
  },
];

export const Material_Default = function () {
  return {
    id: randomID(16),
    name: game.i18n.localize("PF1.WorldConfig.Material.NewName"),
    img: "icons/svg/coins.svg",
    hardness: 10,
    hpPer: 30,
    bypassesDR: [],
  };
};
